version: "3"

services:
  backend:
    container_name: HiQidas_backend
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/HiQidas:cached
    command: sleep infinity
    ports:
      - "7070:7070"
    depends_on:
      - mariadb

  frontend:
    container_name: HiQidas_frontend
    build:
      context: ../dev/frontend
      dockerfile: Dockerfile
    volumes:
      - ../dev/frontend/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "7071:80"
    depends_on:
      - backend

  mariadb:
    container_name: HiQidas_mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: HiQidas
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: HiQidas_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "7072:80"
    depends_on:
      - mariadb

volumes:
  db: null
